url: ""
baseurl: "" # the subpath of your site, e.g. /blog/

# Site settings
# Site settings
title: Mobile Refresh
email: mmegazar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  GDG Wellington, together with Cocoaheads Wellington is proud to bring you Mobile Refresh 2016. Our one-day conference is aimed at mobile technology enthusiasts who are interested in a quick update on the latest developments announced at Google I/O and WWDC.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: GDGWellington

# Team names, titles and social links
# people:
# - name: Kay Garland
#   pic: 1
#   position: Lead Designer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: stack-overflow
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/GDGWellington
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket 
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty